services:
  - type: web
    name: mern-app
    runtime: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mern-db
          property: connectionString
    healthCheckPath: /api/health
databases:
  - name: mern-db
    databaseName: mern
    user: mernuser
    plan: free